---
stages:
  - name: BUILD
    inputs:
      - type: git
        branch: master
        service: ${SAMPLE_REPO}
    triggers:
      - type: commit
    jobs:
      - name: Build
        type: builder
  - name: DEPLOY
    inputs:
      - type: job
        stage: BUILD
        job: Build
    triggers:
      - type: stage
    properties:
      - name: CF_APP_NAME
        value: undefined
        type: text
      - name: APP_URL
        value: undefined
        type: text
    jobs:
      - name: Blue-Green Deploy
        type: deployer
        target:
          region_id: ${PROD_REGION_ID}
          organization: ${PROD_ORG_NAME}
          space: ${PROD_SPACE_NAME}
          application: ${CF_APP_NAME}
          api_key: ${API_KEY}
          cloudant_url: ${CLOUDANT_URL}
        script: |
          #!/bin/bash

          # Push app
          if ! cf app $CF_APP; then  
            cf push $CF_APP --no-start
          else
            OLD_CF_APP=${CF_APP}-OLD-$(date +"%s")
            rollback() {
              set +e  
              if cf app $OLD_CF_APP; then
                cf logs $CF_APP --recent
                cf delete $CF_APP -f
                cf rename $OLD_CF_APP $CF_APP
              fi
              exit 1
            }
            set -e
            trap rollback ERR
            cf rename $CF_APP $OLD_CF_APP
            cf push $CF_APP --no-start
            cf delete $OLD_CF_APP -f
          fi

          SERVICE=$(cf services | grep cloudantNoSQLDB | awk -FcloudantNoSQLDB '{print $1}' | sed -e 's/[[:space:]]*$//')
          if [ '$SERVICE' != '' ]; then
              cf bind-service ${CF_APP} "${SERVICE}"
          else
              cf create-service cloudantNoSQLDB lite cloudant-for-answerstore
              #cf create-service cloudantNoSQLDB standard cloudant-for-answerstore
              cf create-service-key cloudant-for-answerstore answerstore-key
              cf service-key cloudant-for-answerstore answerstore-key | tail -n +2 > cloudant.json
              export CLOUDANT_URL=$(jq --raw-output '.url' cloudant.json)
              export CLOUDANT_CREDS=$(jq ". + {database: \"${CLOUDANT_DATABASE}\"}" cloudant.json)
              cf bind-service $CF_APP cloudant-for-answerstore
          fi

          cf start ${CF_APP}






          # Export app name and URL for use in later Pipeline jobs
          export CF_APP_NAME="$CF_APP"
          export APP_URL=http://$(cf app $CF_APP_NAME | grep -e urls: -e routes: | awk '{print $2}')
          # View logs
          cf logs "${CF_APP}" --recent
